In [1]:
import pandas as pd
import PyUber

In [2]:
imo_source='D1D_PROD_XEUS_CENTRAL'
imo_fab_list="'F32','F42','F12','F22','F52'"

In [3]:
conn =  PyUber.connect(datasource=imo_source)

In [4]:
fab_prod = '8PWNCVB'
ret_name = '8PXMCG'

In [5]:
query = f'''
    SELECT 
        z0.commonname AS common_name
        ,z0.IMOBARCODE
        ,z0.title AS title
        ,'{fab_prod}' AS FAB_PROD
        ,z0.product AS RET_PROD
        ,z0.rev AS rev
        ,z0.layer AS layer
        ,z0.step AS step
        ,z0.platetype AS plate_type
        ,z0.tapeintrend AS tapein_trend
        ,z0.itotrend AS ito_trend
        ,To_Char(z0.itocommit,'yyyy-mm-dd hh24:mi:ss') AS ito_commit
        ,z0.itostatus AS ito_status
        ,z0.retfabrev AS ret_fabrev
        ,z0.fab AS fab
        ,z0.barcode AS barcode
        ,z0.imotrend AS imo_trend
        ,To_Char(z0.imocommit,'yyyy-mm-dd hh24:mi:ss') AS imo_commit
        ,z0.imostatus AS imo_status
        ,To_Char(z0.shipdate,'yyyy-mm-dd hh24:mi:ss') AS shipdate
        ,z0.fabrequireddate AS fab_requireddate
        ,z0.imodotprocess AS imo_dotprocess
        ,z0.imoishot AS imo_ishot
        ,z0.technology AS technology
        ,z0.toengcontact AS to_engcontact
        ,z0.dbnames AS dbnames
        ,To_Char(z0.last_updated_timestamp,'yyyy-mm-dd hh24:mi:ss') AS last_updated_timestamp
    FROM 
        F_IMO_TRIFECTA_DASHBOARD z0
    WHERE
        1=1
        --AND z0.last_updated_timestamp >= SYSDATE - 180 
        AND z0.fab In ({imo_fab_list})     
        AND (
            z0.product LIKE '{ret_name}'
        )
'''

In [6]:
df = pd.read_sql(query, conn)
df

C:\Users\dagarcia\AppData\Local\Temp\ipykernel_21480\1061802609.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

,COMMON_NAME,IMOBARCODE,TITLE,FAB_PROD,RET_PROD,REV,LAYER,STEP,PLATE_TYPE,TAPEIN_TREND,...,IMO_COMMIT,IMO_STATUS,SHIPDATE,FAB_REQUIREDDATE,IMO_DOTPROCESS,IMO_ISHOT,TECHNOLOGY,TO_ENGCONTACT,DBNAMES,LAST_UPDATED_TIMESTAMP
0,PANTHERLAKECPU-UDIE,8PXMCGMT00EA13,0EA13,8PWNCVB,8PXMCG,0,MT0,G,EB6X,12/11/2024,...,2025-08-11 13:15:07,Processing - Active,None,09/06/2025,1278.3-17,None,1278.3,DMJACOB,"8pxmcg_0b.oas,f300288.oas",2025-08-19 05:34:55
1,PANTHERLAKECPU-UDIE,8PXMCGDR60AB4,0AB4,8PWNCVB,8PXMCG,0,DR6,G,AI6N,05/22/2025,...,2025-07-19 00:00:00,Shipped,2025-07-18 15:34:33,07/23/2025,1278.3-17,None,1278.3,REILLYCO,"8pxmcg_0a.oas,f300288.oas",2025-08-14 08:36:32
2,PANTHERLAKECPU-UDIE,8PXMCGNDR0AA4,0AA4,8PWNCVB,8PXMCG,0,NDR,G,AI6N,12/09/2024,...,2025-07-12 00:00:00,Shipped,2025-06-20 06:05:59,07/07/2025,1278.3-17,None,1278.3,DMJACOB,"8pxmcg_0a.oas,f300288.oas",2025-08-19 05:34:55
3,PANTHERLAKECPU-UDIE,8PXMCGPDR0AA3,0AA3,8PWNCVB,8PXMCG,0,PDR,G,AI6N,12/09/2024,...,2025-07-12 00:00:00,Shipped,2025-06-24 09:50:14,07/08/2025,1278.3-17,None,1278.3,DMJACOB,"8pxmcg_0a.oas,f300288.oas",2025-08-19 05:34:55
4,PANTHERLAKECPU-UDIE,8PXMCGPDR0AA4,0AA4,8PWNCVB,8PXMCG,0,PDR,G,AI6N,12/09/2024,...,2025-07-12 00:00:00,Shipped,2025-06-28 01:32:12,07/08/2025,1278.3-17,None,1278.3,DMJACOB,"8pxmcg_0a.oas,f300288.oas",2025-08-19 05:34:55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,PANTHERLAKECPU-UDIE,8PXMCGFT10AA6,0AA6,8PWNCVB,8PXMCG,0,FT1,G,AI6U,12/09/2024,...,2025-07-19 00:00:00,Shipped,2025-08-15 07:13:38,07/24/2025,1278.3-17,None,1278.3,DMJACOB,"8pxmcg_0a.oas,f300288.oas",2025-08-19 05:39:50
205,PANTHERLAKECPU-UDIE,8PXMCGNBM0AB2,0AB2,8PWNCVB,8PXMCG,0,NBM,G,AI6N,07/02/2025,...,2025-09-01 19:54:22,Processing - Active,None,09/10/2025,1278.3-17,None,1278.3,KSHARMA,"8pxmcg_0a.oas,f300288.oas",2025-08-14 09:00:08
206,PANTHERLAKECPU-UDIE,8PXMCGPB20AB2,0AB2,8PWNCVB,8PXMCG,0,PB2,G,AI6N,07/02/2025,...,2025-08-20 00:00:00,Shipped,2025-08-04 17:52:50,07/31/2025,1278.3-17,None,1278.3,KSHARMA,"8pxmcg_0a.oas,f300288.oas",2025-08-14 09:00:08
207,PANTHERLAKECPU-UDIE,8PXMCGPBM0AB2,0AB2,8PWNCVB,8PXMCG,0,PBM,G,AI6N,07/02/2025,...,2025-08-20 00:00:00,Shipped,2025-08-05 01:25:40,07/31/2025,1278.3-17,None,1278.3,KSHARMA,"8pxmcg_0a.oas,f300288.oas",2025-08-14 09:00:08
208,PANTHERLAKECPU-UDIE,8PXMCGVA41AA5,1AA5,8PWNCVB,8PXMCG,1,VA4,G,AI6U,04/06/2025,...,2025-09-07 00:00:00,Processing - Active,None,09/23/2025,1278.3-17,None,1278.3,TDHILL,"8pxmcg_1a.oas,f300288b.oas",2025-08-19 05:46:47

In [7]:
query = f'''
    SELECT  
        substr(RETICLE,1,12) as RETICLE_ID,  min(TXN_DATE) as FirstArriv 
    FROM
        F32S.F_RETICLEHIST
    WHERE RETICLE_PRODUCT in ('8PXMCG')
        and TRANSACTION like 'RetSSRec%' 
        and TXN_DATE  > current_date -360        
    group by
        substr(RETICLE,1,12)
'''

In [8]:
conn2 =  PyUber.connect(datasource='F32_PROD_XEUS')
df2 = pd.read_sql(query, conn2)
df2

C:\Users\dagarcia\AppData\Local\Temp\ipykernel_21480\1275895339.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df2 = pd.read_sql(query, conn2)

      RETICLE_ID          FIRSTARRIV
0   8PXMCGNBM0AB 2025-08-20 21:04:26
1   8PXMCGNDR0AA 2025-06-21 09:47:01
2   8PXMCGVA91AA 2025-08-21 09:02:48
3   8PXMCGBAV0NA 2025-08-27 20:26:31
4   8PXMCGMT11EA 2025-08-27 07:40:44
..           ...                 ...
80  8PXMCGFT10AA 2025-07-18 10:59:17
81  8PXMCGNBM0AA 2025-07-19 19:33:53
82  8PXMCGPBM0AA 2025-07-19 09:20:01
83  8PXMCGMT61NA 2025-08-21 12:55:12
84  8PXMCGPSD0AA 2025-07-22 08:28:38

[85 rows x 2 columns]

In [ ]:
df['RETICLE_ID'] = df['IMOBARCODE'].str[:12]
ret = pd.merge(df, df2, on='RETICLE_ID', how='left')

In [11]:
ret

,COMMON_NAME,IMOBARCODE,TITLE,FAB_PROD,RET_PROD,REV,LAYER,STEP,PLATE_TYPE,TAPEIN_TREND,...,SHIPDATE,FAB_REQUIREDDATE,IMO_DOTPROCESS,IMO_ISHOT,TECHNOLOGY,TO_ENGCONTACT,DBNAMES,LAST_UPDATED_TIMESTAMP,RETICLE_ID,FIRSTARRIV
0,PANTHERLAKECPU-UDIE,8PXMCGMT00EA13,0EA13,8PWNCVB,8PXMCG,0,MT0,G,EB6X,12/11/2024,...,None,09/06/2025,1278.3-17,None,1278.3,DMJACOB,"8pxmcg_0b.oas,f300288.oas",2025-08-19 05:34:55,8PXMCGMT00EA,2025-08-20 08:20:23
1,PANTHERLAKECPU-UDIE,8PXMCGDR60AB4,0AB4,8PWNCVB,8PXMCG,0,DR6,G,AI6N,05/22/2025,...,2025-07-18 15:34:33,07/23/2025,1278.3-17,None,1278.3,REILLYCO,"8pxmcg_0a.oas,f300288.oas",2025-08-14 08:36:32,8PXMCGDR60AB,2025-07-11 04:27:33
2,PANTHERLAKECPU-UDIE,8PXMCGNDR0AA4,0AA4,8PWNCVB,8PXMCG,0,NDR,G,AI6N,12/09/2024,...,2025-06-20 06:05:59,07/07/2025,1278.3-17,None,1278.3,DMJACOB,"8pxmcg_0a.oas,f300288.oas",2025-08-19 05:34:55,8PXMCGNDR0AA,2025-06-21 09:47:01
3,PANTHERLAKECPU-UDIE,8PXMCGPDR0AA3,0AA3,8PWNCVB,8PXMCG,0,PDR,G,AI6N,12/09/2024,...,2025-06-24 09:50:14,07/08/2025,1278.3-17,None,1278.3,DMJACOB,"8pxmcg_0a.oas,f300288.oas",2025-08-19 05:34:55,8PXMCGPDR0AA,2025-06-26 18:24:01
4,PANTHERLAKECPU-UDIE,8PXMCGPDR0AA4,0AA4,8PWNCVB,8PXMCG,0,PDR,G,AI6N,12/09/2024,...,2025-06-28 01:32:12,07/08/2025,1278.3-17,None,1278.3,DMJACOB,"8pxmcg_0a.oas,f300288.oas",2025-08-19 05:34:55,8PXMCGPDR0AA,2025-06-26 18:24:01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
204,PANTHERLAKECPU-UDIE,8PXMCGFT10AA6,0AA6,8PWNCVB,8PXMCG,0,FT1,G,AI6U,12/09/2024,...,2025-08-15 07:13:38,07/24/2025,1278.3-17,None,1278.3,DMJACOB,"8pxmcg_0a.oas,f300288.oas",2025-08-19 05:39:50,8PXMCGFT10AA,2025-07-18 10:59:17
205,PANTHERLAKECPU-UDIE,8PXMCGNBM0AB2,0AB2,8PWNCVB,8PXMCG,0,NBM,G,AI6N,07/02/2025,...,None,09/10/2025,1278.3-17,None,1278.3,KSHARMA,"8pxmcg_0a.oas,f300288.oas",2025-08-14 09:00:08,8PXMCGNBM0AB,2025-08-20 21:04:26
206,PANTHERLAKECPU-UDIE,8PXMCGPB20AB2,0AB2,8PWNCVB,8PXMCG,0,PB2,G,AI6N,07/02/2025,...,2025-08-04 17:52:50,07/31/2025,1278.3-17,None,1278.3,KSHARMA,"8pxmcg_0a.oas,f300288.oas",2025-08-14 09:00:08,8PXMCGPB20AB,2025-08-06 22:08:06
207,PANTHERLAKECPU-UDIE,8PXMCGPBM0AB2,0AB2,8PWNCVB,8PXMCG,0,PBM,G,AI6N,07/02/2025,...,2025-08-05 01:25:40,07/31/2025,1278.3-17,None,1278.3,KSHARMA,"8pxmcg_0a.oas,f300288.oas",2025-08-14 09:00:08,8PXMCGPBM0AB,2025-08-06 22:21:45
208,PANTHERLAKECPU-UDIE,8PXMCGVA41AA5,1AA5,8PWNCVB,8PXMCG,1,VA4,G,AI6U,04/06/2025,...,None,09/23/2025,1278.3-17,None,1278.3,TDHILL,"8pxmcg_1a.oas,f300288b.oas",2025-08-19 05:46:47,8PXMCGVA41AA,2025-08-23 08:55:38